### ISSUE TITLE
Jump[ETHICAL]

### ISSUE THREAD

**Issue by armadillo1234** [City-of-Helsinki/mlops-template#58]
**Report an ethical issue**

THE ISSUE IS PUBLIC, DO NOT WRITE ANY PERSONAL DATA HERE!

The City of Helsinki has eight ethical principles for data & AI. Please describe which principles are or may be violated and how.

The ethical principles for data & AI are:

 - People-orientedness
    - We develop services based on data and AI for the benefit of people and with people in mind.
 - Transparency
    - We communicate as transparently as possible how and where we use data and AI.
 - Explainability
    - We can explain the general operating logic of a single result or algorithm in an understandable way. 
 - Fairness and equality 
    - The basis for the use of data and AI solutions is respect for everyone’s dignity and rights. 
 - Responsibility and maintaining trust
    - For each service that uses AI, we assign a responsible party that our customers can contact.
 - Privacy 
    - We handle personal data carefully and securely throughout the life cycle of the system.
 - Security 
    - Systems using data and AI are well protected and controlled.
 - Under human control
    - The person responsible is able to monitor and control the operations of the system and intervene, if necessary.

**Describe the issue**
A clear and concise description of what the ethical issue is or may be. 

**System information**
If possible, provide information of the device & system where you observed the issue. Hardware, Operating System, Browser etc.

**Screenshots or pictures**
If applicable, add screenshots or pictures to help explain your problem.

**Suggested solution**
You may provide a suggestion on how to improve or fix the issue.

**Additional context**

**Comment by nakytoe** [comment]
Closed as no issue described. Please open new issue with description of an issue if there is any.
